spring.application.name=backend


spring.datasource.url=jdbc:postgresql://localhost:5432/webhook
spring.datasource.username=postgres
spring.datasource.password=postgres


spring.threads.virtual.enabled=true





